{
  imports = [
    ./blink-cmp.nix
    ./bufferline.nix
    ./comment.nix
    ./conform-nvim.nix
    ./copilot-lua.nix
    ./csvview.nix
    ./flash.nix
    ./lazygit.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./markdown-preview.nix
    ./mini-pairs.nix
    ./mini.nix
    ./noice.nix
    ./obsession.nix
    ./obsidian.nix
    ./opencode.nix
    ./persistence.nix
    ./render-markdown.nix
    ./snacks.nix
    ./spectre.nix
    ./tmux-navigator.nix
    ./treesitter.nix
    ./visual-multi.nix
    ./which-key.nix
    ./yanky.nix
    ./yazi.nix
  ];
}
