# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "vmd"
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "noatime"
      "size=3G"
      "mode=755"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/957A-7590";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  boot.initrd = {
    systemd.enable = true;
    luks.devices."enc" = {
      device = "/dev/disk/by-uuid/055580b6-24c9-4c6b-b4d8-eab81bc10224";
      allowDiscards = true;
      crypttabExtraOpts = [ "tpm2-device=auto" ];
    };
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/71a4dc8a-d603-4724-b6f9-26b92eb283d8";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
      "x-systemd.device-timeout=0" # wait for decryption
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/71a4dc8a-d603-4724-b6f9-26b92eb283d8";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "noatime"
      "x-systemd.device-timeout=0" # wait for decryption
    ];
  };

  fileSystems."/home/.snapshots" = {
    device = "/dev/disk/by-uuid/71a4dc8a-d603-4724-b6f9-26b92eb283d8";
    fsType = "btrfs";
    options = [
      "subvol=@home/.snapshots"
      "compress=zstd"
      "noatime"
      "x-systemd.device-timeout=0" # wait for decryption
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/f661bdf4-f8b0-4e55-ac6d-f9337828786b";
      randomEncryption = {
        enable = true;
        allowDiscards = true;
      };
    }
  ];

  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-uuid/CC28EE4576AC5AE3";
    fsType = "ntfs3";
    options = [
      "prealloc"
      "nofail"
      "X-mount.mkdir"
    ];
    neededForBoot = false;
  };

  fileSystems."mnt/hdd1" = {
    device = "/dev/disk/by-uuid/63edc807-ec2a-4461-9a4a-854313c19600";
    fsType = "ext4";
    options = [
      "defaults"
      "nofail"
      "X-mount.mkdir"
    ];
    neededForBoot = false;
  };

  fileSystems."mnt/hdd2" = {
    device = "/dev/disk/by-uuid/f76ce5a0-dd4f-4a1d-851a-3ceb038e0769";
    fsType = "ext4";
    options = [
      "defaults"
      "nofail"
      "X-mount.mkdir"
    ];
    neededForBoot = false;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
